				<div class="factorHead" style="display: none;">
					<h2 id="kerbTitle"><span>&nbsp;</span>用户名和口令</h2>
					<div class="authComplete" style="display: none;">认证完成</div>
				</div>
				<div class="factor" id="kerberos" style="display: none;">
					<table>
						<tr>
							<td><label for="login">登录</label></td>
							<td
							id="login">$l (<a href="/cgi-bin/logout" class="switchUser" id="switchUserR" tabindex="1">切换用户</a>)</td>
						</tr>
						<tr>
							<td><label for="password">口令</label></td>
							<td><input id="password" name="password" type="password" value="" size="18" tabindex="2" /></td>
						</tr>
						<tr class="capsLock" style="display: none;">
							<td>&nbsp;</td>
							<td>大小写锁定键被打开</td>
						</tr>
					</table>
					需要 <a href="#kerbInfo" id="kerbInfoShow" tabindex="7">一个帐号或者忘记口令？</a> </div>
