				<div class="factorHead" style="display: none;">
					<h2 id="kx509Title"><span>&nbsp;</span>证书</h2>
					<div class="authComplete" style="display: none;">认证完成</div>
				</div>
				<div class="factor" id="kx509" style="display: none;">
					<p class="note">您必须安装 k.x-509 软件并且已配置。</p>
					<p>
						<input name="useKX509" id="useKX509" type="checkbox" value="1" tabindex="5" />
						<label for="useKX509">使用证书认证</label>
					</p>
					下载 <a href="#kx509Info" id="kx509InfoShow" tabindex="9">k.x-509 软件</a> </div>
