				<div class="factorHead" style="display: none;">
					<h2 id="inviteloginTitle"><span>&nbsp;</span>邀请码认证</h2>
					<div class="authComplete" style="display: none;">认证完成</div>
				</div>
				<div class="factor" id="invitelogin" style="display: none;">
					<table>
						<tr>
							<td><label for="invite">邀请码</label></td>
							<td><input id="invite" name="invite" type="password" value="" size="18" tabindex="1" /></td>
						</tr>
						<tr class="capsLock" style="display: none;">
							<td>&nbsp;</td>
							<td>大小写锁定键被打开</td>
						</tr>
					</table>
					<a href="#inviteinfo" id="inviteInfoShow" tabindex="7">什么是邀请码？</a> </div>

