				<div class="factorHead" style="display: none;">
					<h2 id="otpTitle"><span>&nbsp;</span>一次性口令</h2>
					<div class="authComplete" style="display: none;">认证完成</div>
				</div>
				<div class="factor" id="otp" style="display: none;">
					<table>
						<tr>
							<td><label for="passcode" id="pCodeLabel">Passcode</label></td>
							<td><input id="passcode" name="passcode" type="password" value="" size="18" tabindex="3" /></td>
						</tr>
						<tr class="capsLock" style="display: none;">
							<td>&nbsp;</td>
							<td>大小写锁定键被打开</td>
						</tr>
					</table>
					管理您的 <a href="#otpInfo" id="otpInfoShow" tabindex="8">令牌</a> </div>
