				<div id="mainInfo">
					<p>在右侧选择任一种登录方式，输入登录信息，之后按 &quot;登录按钮&quot; 完成登录。</p>
					<p class="jsOnly">标记为 <img
					src="/cosign/images/circle.gif" alt="yellow circle" /> 是必须的。</p>
					<p>使用本服务，意味着您已经接受我们的相关政策条款。</p>
					<p class="noScript">这个页面在 JavaScript 启用下有更好的表现。</p>
					$!include(../inc/*.html)
				</div>
				<div id="kerbInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="kerbInfoHide">隐藏本信息</a> <a href="#l2header" class="toTop">返回顶部</a></h4>
					<h3>需要一个帐号？</h3>
					<p>替换本段内容为创建帐号的相关指示...</p>
					<h3>忘记口令？</h3>
					<p>替换本段内容为重置密码的相关指示...</p>
				</div>
				<div id="otpInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="otpInfoHide">隐藏本信息</a> <a href="#l2header" class="toTop">返回顶部</a></h4>
					<h3>获取一个令牌</h3>
					<p>替换本段内容为一次性口令的相关指示...</p>
				</div>
				<div id="kx509Info" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="kx509InfoHide">隐藏本信息</a> <a href="#l2header" class="toTop">返回顶部</a></h4>
					<h3>下载 KX.509</h3>
					<p>服务 KX.509 提供了一个 客户端/服务器 应用，使用 Kerberos 来获取一个短期的 X.509 证书一。
						使得浏览器连接任何 CoSign 保护的网站不再需要输入用户名和口令，而自动登录。 在密歇根大学，
						这项服务由知道唯一名称和 Kerberos 口令的用户使用。</p>
				</div>
				<div id="inviteInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="inviteInfoHide">隐藏本信息</a> <a href="#l2header" class="toTop">返回顶部</a></h4>
					<h3>关于邀请码认证</h3>
					<p>邀请码是由管理员分配的登录密钥。在使用邀请码登录时，您还需要在用户名字段输入您的邮件地址。
					<p>注意：邀请码登录和口令登录互斥，当口令输入框中包含内容时，邀请码输入框自动禁用，反之亦然。
					</p>
				</div>

