<style type="text/css">
  <!--
  body { font-family: arial,sans-serif; background-color: #fff; margin-top: 2; }
  .c { width: 4; height: 4; } 
  a:link { color: #00c; } 
  a:visited { color: #551a8b; }
  a:active { color: #f00; }
  .form-noindent { background-color: #fff; border: 1px solid #c3d9ff; }
  -->
</style>
<style type="text/css"><!--
.gaia.le.lbl { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.fpwd { font-family: Arial, Helvetica, sans-serif; font-size: 70%; }
.gaia.le.chusr { font-family: Arial, Helvetica, sans-serif; font-size: 70%; }
.gaia.le.val { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.button { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.rem { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }

.gaia.captchahtml.desc { font-family: arial, sans-serif; font-size: smaller; } 
.gaia.captchahtml.cmt { font-family: arial, sans-serif; font-size: smaller; font-style: italic; }
  
--></style>
<style type="text/css"><!--
  div.errormsg { color: red; font-size: smaller; font-family:arial,sans-serif; }
  font.errormsg { color: red; font-size: smaller; font-family:arial,sans-serif; }  
--></style>
<style type="text/css"><!--
.gaia.le.lbl { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.fpwd { font-family: Arial, Helvetica, sans-serif; font-size: 70%; }
.gaia.le.chusr { font-family: Arial, Helvetica, sans-serif; font-size: 70%; }
.gaia.le.val { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.button { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }
.gaia.le.rem { font-family: Arial, Helvetica, sans-serif; font-size: smaller; }

.gaia.captchahtml.desc { font-family: arial, sans-serif; font-size: smaller; } 
.gaia.captchahtml.cmt { font-family: arial, sans-serif; font-size: smaller; font-style: italic; }
  
--></style>
 
<style type="text/css"><!--
    .body { margin-left: 3em;
            margin-right: 5em;
            font-family: arial,sans-serif; }

    div.errorbox-good {}

    div.errorbox-bad {} 

    div.errormsg { color: red; font-size: smaller; font-family: arial,sans-serif;}
    font.errormsg { color: red; font-size: smaller; font-family: arial,sans-serif;}
    
    hr {
      border: 0;
      background-color:#DDDDDD;
      height: 1px;
      width: 100%;
      text-align: left;
      margin: 5px;
    }
    
--></style>
<style type="text/css"><!--
#error {
	border: 1px dotted #cc9999;
	margin-bottom: 10px;
	padding: 6px 8px 6px 28px;
	background: url(images/icon_alert.gif) left center no-repeat;
	background-color: #fcfcfc;
	color: #cc0000;
}
#foot {
	width: 760px;
	margin: 20px auto;
	text-align: center;
	padding: 5px;
	font-size: 108%;
	border-top: 1px solid #ccc;
}

#foot,
#foot a {
	background-color: inherit;
	color: #999;
}

#foot a:hover {
	background-color: inherit;
	color: #70a8f1;
}
--></style>
