				<div class="factorHead" style="display: none;">
					<h2 id="otpTitle"><span>&nbsp;</span>$!_("One Time Passcode")</h2>
					<div class="authComplete" style="display: none;">$!_("Authentication Complete")</div>
				</div>
				<div class="factor" id="otp" style="display: none;">
					<table>
						<tr>
							<td><label for="passcode" id="pCodeLabel">$!_("Passcode")</label></td>
							<td><input id="passcode" name="passcode" type="password" value="" size="18" tabindex="3" /></td>
						</tr>
						<tr class="capsLock" style="display: none;">
							<td>&nbsp;</td>
							<td>$!_("Caps Lock is on")</td>
						</tr>
					</table>
					<a href="#otpInfo" id="otpInfoShow" tabindex="8">$!_("Manage your token")</a> </div>
