				<div id="mainInfo">
					<p>$!_("Please enter your authentication information and click the &quot;Log&nbsp;In&quot; button"
					  " to continue.")</p>
					<p class="jsOnly">$!_("Authentication"
					  " sections marked with a <img"
					  " src=\"/cosign/images/circle.gif\" alt=\"yellow circle\" /> are"
					  " required.")</p>
					<p>$!_("By using this service you agree to adhere to our policies and guidelines.")</p>
				</div>
				<p class="noScript">$!_("This page displays best when JavaScript is enabled in your web"
				  " browser.")</p>

				<div id="kerbInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="kerbInfoHide">$!_("Hide this Information")</a> <a href="#l2header" class="toTop">$!_("Back"
					  " to Top")</a></h4>
					<h3>$!_("Need an Account?")</h3>
					<p>$!_("Replace this text with information about obtaining an account. Lorem ipsum dolor"
					  " sit amet, consectetuer adipiscing elit. Nullam cursus dolor non lacus. Aenean vitae"
					  " orci. Mauris vulputate ornare urna.")</p>
					<h3>$!_("Forgot Your Password?")</h3>
					<p>$!_("Replace this text with information about resetting your password. Lorem ipsum"
					  " dolor sit amet, consectetuer adipiscing elit. Nullam cursus dolor non lacus. Aenean"
					  " vitae orci. Mauris vulputate ornare urna.")</p>
				</div>
				<div id="otpInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="otpInfoHide">$!_("Hide this Information")</a> <a href="#l2header" class="toTop">$!_("Back"
					  " to Top")</a></h4>
					<h3>$!_("Get a Token")</h3>
					<p>$!_("Replace this with text about using one time passcodes. Lorem ipsum dolor sit amet,"
					  " consectetuer adipiscing elit. Nullam cursus dolor non lacus. Aenean vitae orci."
					  " Mauris vulputate ornare urna.")</p>
				</div>
				<div id="kx509Info" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="kx509InfoHide">$!_("Hide this Information")</a> <a href="#l2header" class="toTop">$!_("Back"
					  " to Top")</a></h4>
					<h3>$!_("Download KX.509")</h3>
					<p>$!_("The KX.509 service provides a client/server application that uses Kerberos to"
					  " acquire a short-term X.509 certificate. This makes it possible for web-browsers"
					  " to authenticate a user to any CoSign-protected web services silently instead of"
					  " prompting the user for a name and password. At U-M, this service can be used by"
					  " those who know their Uniqname and Kerberos password.")</p>
				</div>
				<div id="inviteInfo" class="infoBox">
					<h4><a href="#mainInfo" class="hideInfo" id="inviteInfoHide">$!_("Hide this Information")</a> <a href="#l2header" class="toTop">$!_("Back"
					  " to Top")</a></h4>
					<h3>$!_("About invite code")</h3>
					<p>$!_("Invite code is assigned by administrator. Before input your invite code, you must provide your email address as your login name.")
          </p>
					<p>$!_("Note: The two fields, password and invite code input fields are exclusive. The other is disabled when one is focus and has inupt.")
					</p>
				</div>
