				<div class="factorHead" style="display: none;">
					<h2 id="kx509Title"><span>&nbsp;</span>$!_("Certificate")</h2>
					<div class="authComplete" style="display: none;">$!_("Authentication Complete")</div>
				</div>
				<div class="factor" id="kx509" style="display: none;">
					<p class="note">$!_("You must have k.x-509 software installed and configured.")</p>
					<p>
						<input name="useKX509" id="useKX509" type="checkbox" value="1" tabindex="4" />
						<label for="useKX509">$!_("Authenticate using a certificate")</label>
					</p>
					$!_("Download") <a href="#kx509Info" id="kx509InfoShow" tabindex="9">$!_("k.x-509 software")</a> </div>
