  <table id="header" border="0" cellpadding="2" cellspacing="0" width="100%">
    <tbody>
      <tr>
        <td colspan="2"><img alt="" height="2" width="1"></td>
      </tr>
      <tr>
        <td valign="top" width="1%">
          <a href="https://weblogin.foo.bar/">
          <img src="/cosign/images/services/Cosign_3d.gif" alt="CoSign" align="left" border="0">
          </a>
        </td>
        <td valign="bottom">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tbody>
              <tr>
                <td colspan="2"><img alt="" height="15" width="1"></td>
              </tr>
              <tr bgcolor="#3366cc">
                <td><img alt="" height="1" width="1"></td>
              </tr>
              <tr bgcolor="#C3D9FF">
                <td style="padding-left: 4px; padding-bottom: 9px; padding-top: 9px; font-family: arial,sans-serif;">
                  <b>$!_("Single SignOn")</b>
                </td>
              </tr>
              <tr>
                <td colspan="2"><img alt="" height="5" width="1"></td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
