	<ul class="text">
		<li><a href="#instruct" title="$!_("Jump to the Web Login instructions") [ALT + 1 Windows / CONTROL + 1 Mac]" accesskey="1">$!_("Jump to the Web Login instructions")</a></li>
		<li><a href="#error" title="$!_("Jump to the error message (if present)") [ALT + 2 Windows / CONTROL + 2 Mac]" accesskey="2">$!_("Jump to the error message (if present)")</a></li>
		<li><a href="#kerberos" title="$!_("Jump to the ID and Password section") [ALT + 3 Windows / CONTROL + 3 Mac]" accesskey="3">$!_("Jump to the ID and Password section")</a></li>
		<li><a href="#otp" title="$!_("Jump to the One Time Passcode section") [ALT + 4 Windows / CONTROL + 4 Mac]"  accesskey="4">$!_("Jump to the One Time Passcode section")</a></li>
		<li><a href="#kx509" title="$!_("Jump to the Certificate section") [ALT + 5 Windows / CONTROL + 5 Mac]" accesskey="5">$!_("Jump to the Certificate section")</a></li>
	</ul>
